import type { Metadata } from "next";
import AppWrapper from "@/components/AppWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AppWrapper>{props.children}</AppWrapper>
      </body>
    </html>
  );
}
